# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_install_hook_types: [pre-commit, pre-push, commit-msg]

repos:
  
  - repo: local
    hooks:
      - id: make-fmt
        name: Format code
        entry: make test
        language: system
        pass_filenames: false
        stages: [pre-commit]

  - repo: local
    hooks:
      - id: make-test
        name: Test
        entry: make test
        language: system
        pass_filenames: false
        stages: [pre-commit]

  - repo: 'https://github.com/compilerla/conventional-pre-commit'
    rev: v3.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
  